language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test user.tests
  - python manage.py test car.tests
  - python manage.py test car.avio
  - python manage.py test car.hotels