version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
  web:
    build: .
    image: isa:latest
    env_file: 
      - ".env"
    restart: unless-stopped
    ports:
      - "8010:80"
    links:
      - db

