version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
       - ./storage/db:/var/lib/postgresql/data
  web:
    image: jrubics/isa
    env_file: 
      - ".env"
    restart: unless-stopped
    ports:
      - "8010:80"
    links:
      - db