version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
  web:
    build: .
    image: isa:latest
    restart: unless-stopped
    ports:
      - "8010:8000"
    links:
      - db

