version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: jelena_isa_db
    volumes:
       - ./db:/var/lib/postgresql/data
  web:
    image: jrubics/isa
    env_file: 
      - ".env"
    restart: unless-stopped
    container_name: jelena_isa_web
    ports:
      - "8010:80"
    links:
      - db