# Generated by Django 2.1.3 on 2019-01-28 20:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest_number', models.PositiveIntegerField()),
                ('room_number', models.PositiveIntegerField()),
                ('min_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
                ('rooms', models.ManyToManyField(to='hotels.HotelRoom')),
                ('services', models.ManyToManyField(to='hotels.HotelService')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='check_in',
            field=models.DateField(default=datetime.date(2019, 1, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='check_out',
            field=models.DateField(default=datetime.date(2019, 1, 28)),
            preserve_default=False,
        ),
    ]
