# Generated by Django 2.1.3 on 2019-02-01 00:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest_number', models.PositiveIntegerField()),
                ('room_number', models.PositiveIntegerField()),
                ('min_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rooms_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('services_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
                ('rooms', models.ManyToManyField(to='hotels.HotelRoom')),
            ],
        ),
        migrations.CreateModel(
            name='QuickReservationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelRoom')),
            ],
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='check_in',
            field=models.DateField(default=datetime.date(2019, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='check_out',
            field=models.DateField(default=datetime.date(2019, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='guest_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='rooms_charge',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'Charge cannot be negative')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='services_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'Charge cannot be negative')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='services',
            field=models.ManyToManyField(blank=True, to='hotels.HotelService'),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='type_of_charge',
            field=models.CharField(choices=[('per person/day', 'per person/day'), ('per person', 'per person'), ('per room/day', 'per room/day'), ('per room', 'per room')], default='per person/day', max_length=15),
        ),
        migrations.AddField(
            model_name='quickreservationoption',
            name='services',
            field=models.ManyToManyField(to='hotels.HotelService'),
        ),
        migrations.AddField(
            model_name='quickreservationoption',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelShoppingCart'),
        ),
        migrations.AddField(
            model_name='hotelshoppingcart',
            name='services',
            field=models.ManyToManyField(blank=True, to='hotels.HotelService'),
        ),
        migrations.AddField(
            model_name='hotelshoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
