# Generated by Django 2.1.3 on 2019-01-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190128_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelshoppingcart',
            name='services',
            field=models.ManyToManyField(blank=True, to='hotels.HotelService'),
        ),
    ]
