# Generated by Django 2.1.3 on 2019-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20190129_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='type_of_charge',
            field=models.CharField(choices=[('per person/day', 'per person/day'), ('per person', 'per person'), ('per room/day', 'per room/day'), ('per room', 'per room')], default='per person/day', max_length=15),
        ),
    ]
