# Generated by Django 2.1.5 on 2019-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelshoppingcart',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelshoppingcart',
            name='check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelshoppingcart',
            name='guest_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelshoppingcart',
            name='room_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
