# Generated by Django 2.1.3 on 2019-01-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20190129_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelshoppingcart',
            name='rooms_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelshoppingcart',
            name='services_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
