# Generated by Django 2.1.5 on 2019-02-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20190208_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelshoppingcart',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
