# Generated by Django 2.1.3 on 2019-01-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20190130_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReservationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelShoppingCart')),
            ],
        ),
    ]
