# Generated by Django 2.1.3 on 2019-01-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_quickreservationoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickreservationoption',
            old_name='hsc',
            new_name='shopping_cart',
        ),
        migrations.RenameField(
            model_name='quickreservationoption',
            old_name='rooms_total',
            new_name='total_charge',
        ),
        migrations.RemoveField(
            model_name='quickreservationoption',
            name='services_total',
        ),
    ]
