# Generated by Django 2.1.3 on 2019-01-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20190130_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickreservationoption',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelRoom'),
            preserve_default=False,
        ),
    ]
