# Generated by Django 2.1.3 on 2019-01-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_quickreservationoption_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickreservationoption',
            old_name='total_charge',
            new_name='rooms_charge',
        ),
        migrations.AddField(
            model_name='quickreservationoption',
            name='services',
            field=models.ManyToManyField(to='hotels.HotelService'),
        ),
        migrations.AddField(
            model_name='quickreservationoption',
            name='services_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
