# Generated by Django 2.1.2 on 2018-11-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(choices=[('0', 'Other'), ('1', 'Reno'), ('2', 'Opel'), ('3', 'Ford'), ('4', 'Fiat'), ('5', 'Toyota'), ('6', 'BMV'), ('7', 'Mercedes'), ('8', 'Peugeot')], default=0, max_length=1)),
                ('model', models.CharField(max_length=30)),
                ('car_type', models.CharField(choices=[('1', 'City car'), ('2', 'Big car'), ('3', 'Truck'), ('4', 'Motorcycle')], default=1, max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('year', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('promo_description', models.TextField()),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Service'),
        ),
    ]
