# Generated by Django 2.1.2 on 2018-11-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=60)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Service')),
            ],
        ),
    ]
