# Generated by Django 2.1.5 on 2019-01-11 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0004_auto_20190109_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField(default=datetime.datetime.now)),
                ('date2', models.DateTimeField(default=datetime.datetime.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car')),
                ('office1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office1', to='car.BranchOffice')),
                ('office2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office2', to='car.BranchOffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
