# Generated by Django 2.1.5 on 2019-01-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_taken',
        ),
    ]
