# Generated by Django 2.1.5 on 2019-01-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_remove_car_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_taken',
            field=models.BooleanField(default=0),
        ),
    ]
