# Generated by Django 2.1.5 on 2019-01-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_car_is_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_rate', models.PositiveIntegerField()),
                ('service_rate', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Reservation')),
            ],
        ),
    ]
