# Generated by Django 2.1.5 on 2019-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='on_sale',
            field=models.BooleanField(default=0),
        ),
    ]
