# Generated by Django 2.1.5 on 2019-01-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_car_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.Car'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='office1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='office1', to='car.BranchOffice'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='office2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='office2', to='car.BranchOffice'),
        ),
    ]
