# Generated by Django 2.1.5 on 2019-02-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_carrate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='office1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office1', to='car.BranchOffice'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='office2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office2', to='car.BranchOffice'),
        ),
    ]
