# Generated by Django 2.1.5 on 2019-01-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightleg',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avio.Flight'),
        ),
    ]
