# Generated by Django 2.1.5 on 2019-01-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0002_auto_20190123_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_city',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='avio_company',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_city',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='FlightLeg',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
