# Generated by Django 2.1.5 on 2019-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0004_flight_flightleg_seat_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('B', 'Bought ticket'), ('R', 'Reserved ticket')], max_length=1),
        ),
    ]
