# Generated by Django 2.1.5 on 2019-01-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0007_auto_20190127_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'seat_type', 'flight')},
        ),
    ]
