# Generated by Django 2.1.5 on 2019-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0008_auto_20190128_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(choices=[('T', 'Taken seats'), ('F', 'Free seat'), ('P', 'Promotion seat'), ('O', 'Out of order'), ('R', 'Reserved seat')], max_length=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('B', 'Business seats'), ('F', 'First class seats'), ('E', 'Economy seats')], max_length=1),
        ),
    ]
