# Generated by Django 2.1.5 on 2019-01-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0009_auto_20190129_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageSeats',
            fields=[
            ],
            options={
                'verbose_name': 'Mange seate',
                'proxy': True,
                'indexes': [],
            },
            bases=('avio.seat',),
        ),
    ]
