# Generated by Django 2.1.5 on 2019-01-30 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avio', '0010_manageseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passport',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('B', 'Bought ticket'), ('R', 'Reserved ticket'), ('P', 'Promotion ticket')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='time of ticket creation'),
        ),
    ]
