# Generated by Django 2.1.5 on 2019-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0011_auto_20190130_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
