# Generated by Django 2.1.5 on 2019-01-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0012_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviocompany',
            name='additional_services',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='aviocompany',
            name='cabine_luggage_description',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='aviocompany',
            name='luggage',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
