# Generated by Django 2.1.5 on 2019-02-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0015_auto_20190202_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Avio company profit summary',
                'verbose_name_plural': 'Avio company profit summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('avio.ticket',),
        ),
        migrations.AlterModelOptions(
            name='manageseats',
            options={'verbose_name': 'Mange seats'},
        ),
    ]
