# Generated by Django 2.1.5 on 2019-02-03 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avio', '0016_auto_20190203_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_rate', models.PositiveIntegerField()),
                ('company_rate', models.PositiveIntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avio.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
