# Generated by Django 2.1.5 on 2019-02-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0017_flightrate'),
        ('avio', '0017_auto_20190204_1522'),
    ]

    operations = [
    ]
