# Generated by Django 2.1.5 on 2019-02-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20190204_2044'),
        ('avio', '0018_merge_20190204_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereservation',
            name='car_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Reservation'),
        ),
    ]
