# Generated by Django 2.1.5 on 2019-02-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190201_2258'),
        ('avio', '0019_packagereservation_car_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereservation',
            name='city',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='packagereservation',
            name='country',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='packagereservation',
            name='hotel_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.HotelReservation'),
        ),
        migrations.AlterField(
            model_name='packagereservation',
            name='car_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Reservation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='package_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avio.PackageReservation'),
        ),
    ]
