# Generated by Django 2.1.5 on 2019-02-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0019_packagereservation_car_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='package_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avio.PackageReservation'),
        ),
    ]
