# Generated by Django 2.1.5 on 2019-02-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190201_2258'),
        ('avio', '0020_auto_20190205_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereservation',
            name='hotel_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelReservation'),
        ),
    ]
