# Generated by Django 2.1.5 on 2019-02-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0021_packagereservation_hotel_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereservation',
            name='car_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Reservation'),
        ),
        migrations.AlterField(
            model_name='packagereservation',
            name='hotel_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.HotelReservation'),
        ),
    ]
