# Generated by Django 2.1.5 on 2019-01-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181105_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
