# Generated by Django 2.1.5 on 2019-01-25 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avio', '0006_auto_20190123_1845'),
        ('user', '0006_profile_avio_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avio_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avio.AvioCompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_car_admin', 'Is car admin'), ('is_hotel_admin', 'Is hotel admin'), ('is_flight_admin', 'Is flight admin'), ('is_master_admin', 'Is master admin')),
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avio_admin',
        ),
    ]
