# Generated by Django 2.1.5 on 2019-01-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190125_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
