# Generated by Django 2.1.5 on 2019-02-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190128_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
