# Generated by Django 2.1.5 on 2019-02-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_adminuser_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='avio_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avio.AvioCompany'),
        ),
    ]
