# Generated by Django 2.1.5 on 2019-02-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avio', '0019_packagereservation_car_reservation'),
        ('user', '0014_auto_20190205_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avio.PackageReservation'),
        ),
    ]
