# Generated by Django 2.1.5 on 2019-02-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_active_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avio.PackageReservation'),
        ),
    ]
