# Generated by Django 2.1.5 on 2019-02-07 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190206_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPointReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(1, 'Minimum is 1%'), django.core.validators.MaxValueValidator(10, 'Maximum is 100%')])),
                ('hotel_discount', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0, 'Percentage is between 0 and 100'), django.core.validators.MaxValueValidator(100, 'Percentage is between 0 and 100')])),
                ('carservice_discount', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, 'Percentage is between 0 and 100'), django.core.validators.MaxValueValidator(100, 'Percentage is between 0 and 100')])),
            ],
        ),
    ]
