# Generated by Django 2.1.5 on 2019-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_discountpointreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
